#!/bin/bash
nfs_stat=$1

if [ -z $nfs_stat ]; then
	echo "ZBX_NOTSUPPORTED"
else
	if [ `find /tmp -name "nfsstats" -mmin 1 -type f | wc -l` -eq 0 ]; then
		cat /proc/net/rpc/nfs > /tmp/nfsstats
	fi
	#NET
	read NET PACKETS UDP_PACKETS TCP_PACKETS TCP_CONN < <(cat /tmp/nfsstats | grep "net")
	#RPC
	read RPC CALLS RETRANS AUTHREFRSH < <(cat /tmp/nfsstats | grep "rpc")
	#PROC3
	read PROC3 XX NULL GETATTR SETATTR LOOKUP ACCESS READLINK READS WRITES CREATE MKDIR SYMLINK MKNOD REMOVE RMDIR RENAME LINK READDIR READDIRPLUS FSSTAT FSINFO PATHCONF COMMIT < <(cat /tmp/nfsstats | grep "proc3")
	#PROC4OPS
#	read PROC4OPS XX OP0_UNUSED OP1_UNUSED OP2_FUTURE ACCESS CLOSE COMMIT CREATE DELEGPURGE DELEGRETURN GETATTR GETFH LINK LOCK LOCKT LOCKU LOOKUP LOOKUP_ROOT NVERIFY OPEN OPENATTR OPEN_CONF OPEN_DGRD PUTFH PUTPUBFH PUTROOTFH READ READDIR READLINK REMOVE RENAME RENEW RESTOREFH SAVEFH SECINFO SETATTR SETCLTID SETCLTIDCONF VERIFY WRITE RELLOCKOWNER < <(cat /tmp/nfsstats | grep "proc4ops")
	echo ${!nfs_stat}
fi
